version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/quote_server
hooks:
  AfterInstall:
   - location: scripts/installDep
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start
     timeout: 300
     runas: root