version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: scripts/installDep
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: scripts/start
     timeout: 300
     runas: ec2-user