version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: quoterepo/serverSide
    environment:
      - NODE_ENV=production
    volumes:
      - ./://Users/tony/quoterepo/quoterepo_anthony
    expose:
      - "3000"
    command: "npm start"